version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: ["scripts/wait-for-it.sh", "db:5432", "--", "yarn", "watch"]
    volumes:
      - .:/app:delegated
    ports:
      - "1337:1337" # for the app itself
      - "8888:8888" # for viewing analyze-webpack
      - "8080:8080" # for serving test coverage html
    depends_on:
      - db
    environment:
      JWT_SECRET: 'shhHhh...'
      USER_AUDITOR: federalist
      FEATURE_PROXY_EDGE_LINKS: 'true'
      FEATURE_PROXY_EDGE_DYNAMO: 'true'
      FEATURE_ADMIN_AUTH: 'true'
      APP_HOSTNAME: http://localhost:1337
  admin-client:
    image: node:14.15
    working_dir: /app
    volumes:
      - ./admin-client:/app
      - ~/Library/Caches/Yarn:/usr/local/share/.cache/yarn
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - app
    command: ["yarn", "dev"]
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # expose db on host at port 5433
    environment:
      POSTGRES_DB: federalist
      POSTGRES_TEST_DB: federalist-test
      POSTGRES_PASSWORD: password
volumes:
  db-data:
