version: 2.1

##################################
##            Anchors           ##
##################################
default-docker-node: &default-docker-node
  image: circleci/node:12
  environment:
    YARN_VERSION: 0.24.6-1
    CC_TEST_REPORTER_ID: 101a439651b6abd27e5440028a53b5b8f08fe0889f3948d5f58f6cf9f7c786a0

default-docker-postgres: &default-docker-postgres
  image: circleci/postgres:9.6
  environment:
    POSTGRES_USER: ci-test-user
    POSTGRES_DB: federalist-ci-test
    POSTGRES_HOST_AUTH_METHOD: trust

maybe-configure-staging: &maybe-configure-staging
  when:
    condition:
      equal: [ staging, << pipeline.git.branch >> ]
    steps:
      run:
        name: Setup Staging Environment
        command: |
          echo "export CF_USERNAME=$CF_USERNAME_STAGING" >> $BASH_ENV
          echo "export CF_PASSWORD=$CF_PASSWORD_STAGING" >> $BASH_ENV
          echo "export CF_SPACE=staging" >> $BASH_ENV
          echo "export CF_APP=federalistapp-staging" >> $BASH_ENV
          echo "export CF_VARS_FILE=./.cloudgov/vars/staging.yml" >> $BASH_ENV

maybe-configure-production: &maybe-configure-production
  when:
    condition:
      equal: [ main, << pipeline.git.branch >> ]
    steps:
      run:
        name: Setup Production Environment
        command: |
          echo "export CF_USERNAME=$CF_USERNAME_PRODUCTION" >> $BASH_ENV
          echo "export CF_PASSWORD=$CF_PASSWORD_PRODUCTION" >> $BASH_ENV
          echo "export CF_SPACE=production" >> $BASH_ENV
          echo "export CF_APP=federalistapp" >> $BASH_ENV
          echo "export CF_VARS_FILE=./.cloudgov/vars/production.yml" >> $BASH_ENV

install-and-log-into-cloudgov: &install-and-log-into-cloudgov
  run:
    name: Install and log into CF7
    command: |
      curl -L -o cf7.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=v7&source=github'
      sudo dpkg -i cf7.deb
      rm cf7.deb
      cf7 api https://api.fr.cloud.gov
      cf7 login -u $CF_USERNAME -p $CF_PASSWORD -o gsa-18f-federalist -s $CF_SPACE

log-out-of-cloudgov: &log-out-of-cloudgov
  run:
    name: Log out from Cloud.gov
    command: cf7 logout


##################################
##             Jobs             ##
##################################
jobs:
  build:
     docker:
       - *default-docker-node
       - *default-docker-postgres
     environment:
       FEATURE_ADMIN_AUTH: 'true'
     steps:
      - checkout
      - run:
          name: Display versions
          command: |
            echo $(node --version)
            echo $(yarn --version)
            echo $(npm --version)

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn

      - run:
          name: Lint changed files
          command: scripts/lint-ci-pr.sh

      - run:
          name: CodeClimate before-build
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: yarn test:cover
      - run:
          name: CodeClimate combine and upload coverage
          command: |
            # Combine the test coverage reports in coverage/server/ and coverage/client/
            ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.client.json coverage/client/lcov.info
            ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.server.json coverage/server/lcov.info
            ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
            # Attempt to submit a report, but don't fail the build if this fails (`|| true`)
            ./cc-test-reporter upload-coverage || true

  deploy:
    docker:
      - image: circleci/node:12
    environment:
      CF_MANIFEST: ./.cloudgov/manifest.yml
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build app
          command: yarn build
      - *maybe-configure-staging
      - *maybe-configure-production
      - *install-and-log-into-cloudgov
      - deploy:
          command: ./.cloudgov/deploy.sh
      - *log-out-of-cloudgov

  deploy-admin:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-admin-{{ checksum "admin-client/yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ./.cache
          working_directory: ~/admin-client
      - save_cache:
          key: dependency-cache-admin-{{ checksum "admin-client/yarn.lock" }}
          paths:
            - ./admin-client/node_modules
            - ./admin-client/.cache/yarn
      - run:
          name: Build app
          command: yarn build
          working_directory: ~/admin-client
          environment:
            NODE_ENV: production
            API_URL: https://federalistapp-staging.18f.gov
      - *maybe-configure-staging
      - *install-and-log-into-cloudgov
      - run:
          name: Deploy admin
          command: cf7 push federalist-admin-staging --vars-file $CF_VARS_FILE -f $CF_MANIFEST
          environment:
            CF_MANIFEST: ./.cloudgov/manifest.yml
      - *log-out-of-cloudgov

  nightly-builds:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - *maybe-configure-staging
      - *maybe-configure-production
      - *install-and-log-into-cloudgov
      - run:
          name: Run nightly builds
          command: cf7 run-task $CF_APP --name nightly-builds --command "yarn nightly-builds"
      - *log-out-of-cloudgov


##################################
##          Workflows           ##
##################################
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - staging
                - main
      - deploy-admin:
          requires:
            - build        
          filters:
            branches:
              only: staging
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - staging
                - main
    jobs:
      - nightly-builds