name: Security Considerations

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]

jobs:
  security-considerations:
    runs-on: ubuntu-latest
    steps:
      - uses: cloud-gov/security-considerations-action@main
